export const dynamic = 'force-static';
const steps = [
 ['01','Explore','Find the opportunity.','Start with the problem, the people it affects and what a useful outcome would look like.'],
 ['02','Test','Make the idea tangible.','Use AI to prototype quickly, challenge assumptions and learn what deserves to be built.'],
 ['03','Develop','Build for real use.','Turn the strongest ideas into practical technology, shaped around the people who will use it.'],
 ['04','Launch','Prepare for what comes next.','Bring the product towards market with a clear use case, a considered experience and a plan to keep learning.'],
];
export default function Page(){return <>
<section className="hero" aria-labelledby="hero-title"><div className="eyebrow"><span className="dot"/>LONDON-BASED AI LAB</div><h1 id="hero-title">Ambitious ideas.<br/><span>Made useful.</span></h1><div className="hero-bottom"><div className="hero-caption">Independent thinking.<br/>Practical technology.</div><div><p className="hero-lead">Cybernetic is a London-based AI lab. We turn bold what-ifs into technology that changes how people work.</p><div className="actions"><a className="button" href="#contact">Build with us <span aria-hidden="true">↗</span></a><a className="text-link" href="#work">See how we work <span aria-hidden="true">↓</span></a></div></div></div></section>
<section className="approach section" id="approach"><div className="section-top"><span className="eyebrow">01 / OUR APPROACH</span><h2>Move the idea forward.<br/>Learn at every step.</h2></div><div className="steps">{steps.map(([n,label,title,body])=><article key={n}><div className="step-label"><span>{n}</span>{label}</div><h3>{title}</h3><p>{body}</p></article>)}</div></section>
<section className="work section" id="work"><div className="section-top"><span className="eyebrow">02 / BUILD WITH US</span><div><h2>Bring the question.<br/>Let’s build the answer.</h2><p className="section-lead">An idea worth exploring. A workflow that could work better. A product ready for its next step. Our AI consultancy and product-development work starts there.</p></div></div><div className="service-list">{[
['Find your starting point','Explore where AI could be useful, identify the problem to solve and decide which assumptions to test.'],
['Test an idea','Develop a prototype that makes the opportunity concrete and gives you something useful to learn from.'],
['Develop a product','Shape the experience and build the technology around a clear purpose.'],
['Prepare to launch','Work through the practical steps between a working product and bringing it to market.']
].map(([title,body],i)=><article key={title}><span className="index">0{i+1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
<section className="training section" id="training-consulting" aria-labelledby="training-title"><div className="section-top"><span className="eyebrow">03 / TRAINING &amp; CONSULTING</span><div><h2 id="training-title">Build the capability.<br/>Move the work forward.</h2><p className="section-lead">Our team brings experience from Meta, the Financial Times and Publicis.</p></div></div><div className="service-list"><article><span className="index">01</span><h3>Training</h3><p>Help your team understand AI, get hands-on with the tools and apply what they learn to real work.</p></article><article><span className="index">02</span><h3>Consulting</h3><p>Find where AI can make a difference, decide what’s worth pursuing and turn promising ideas into practical next steps.</p></article><div className="actions"><a className="button" href="https://docs.google.com/forms/d/e/1FAIpQLScReKJN7OHvYjDk5DPu1sbOzkq5iuRjEH2UzJ3jGJMPF1nWXw/viewform">Let’s talk <span aria-hidden="true">↗</span></a></div></div></section>
<section className="contact section" id="contact"><div className="eyebrow">04 / START A CONVERSATION</div><h2>What are you<br/><span>thinking about?</span></h2><div className="contact-bottom"><p>Tell us about your idea, the problem you want to solve or the opportunity you see.</p><div><a className="button" href="https://docs.google.com/forms/d/e/1FAIpQLScReKJN7OHvYjDk5DPu1sbOzkq5iuRjEH2UzJ3jGJMPF1nWXw/viewform">Build with us <span aria-hidden="true">↗</span></a><p className="microcopy">Opens a short Google Form. Please avoid sharing credentials or confidential information.</p></div></div></section>
</>}
